spring.application.name=pos-compra

# PORT
server.port=4444

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/compra_mc
spring.datasource.username=postgres
spring.datasource.password=postgresql626
spring.datasource.driver-class-name=org.postgresql.Driver
database.name=compra_mc

# CORS
cors.allowed.origins=http://localhost:3000,https://frontend-sca-manager.vercel.app,http://localhost:3001,http://localhost:3002,http://localhost:3003

# HABILITA EL SERVIDOR EUREKA
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# CREDENCIALES DEL API GATEWAY
service.security.secure-key-username=jorge33Username
service.security.secure-key-password=jorge33Password!