spring.application.name=pos-microservicio-eureka

server.port=8761

eureka.client.service-cliente-url.defaultZone=http://localhost:${server.port}/eureka/

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false