spring.application.name=pos-api-gateway

# PORT
server.port=5555

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/api_gateway_mc
spring.datasource.username=postgres
spring.datasource.password=postgresql626
spring.datasource.driver-class-name=org.postgresql.Driver
database.name=api_gateway_mc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORS
cors.allowed.origins=http://localhost:3000,https://frontend-sca-manager.vercel.app,http://localhost:3001,http://localhost:3002,http://localhost:3003

# SECRET KEY JWT
jwt.key.secret=KeyFigueroa626007!KeyFigueroa626007!KeyFigueroa626007!KeyFigueroa626007!
# 1 dia = 24 hora = mil seg
jwt.key.expiration=86400000

# HABILITA EL SERVIDOR EUREKA
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# CREDENCIALES DEL API GATEWAY
service.security.secure-key-username=jorge33Username
service.security.secure-key-password=jorge33Password!

# API INMUEBLES
inmueble.service.base.url=http://localhost:3333
inmueble.service.api.path=/api/inmueble
inmueble.service.name.value=inmueble-service

# API COMPRAS
compra.service.base.url=http://localhost:4444
compra.service.api.path=/api/compra
compra.service.name.value=compra-service
